#############################################################################
# Makefile for building: PasswordGuard
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  PasswordGuard.pro
# Template: app
# Command: /home/halilibrahim/Qt/5.15.2/gcc_64/bin/qmake -o Makefile PasswordGuard.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/halilibrahim/Qt/5.15.2/gcc_64/include -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQuick -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQmlModels -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/halilibrahim/Qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/halilibrahim/Qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/halilibrahim/Qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PasswordGuard1.0.0
DISTDIR = /media/halilibrahim/yeni_birim/QT_Projeler/PasswordGuard/.tmp/PasswordGuard1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/halilibrahim/Qt/5.15.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Quick.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Gui.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5QmlModels.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Qml.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Network.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Sql.so /home/halilibrahim/Qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		passwordanalyzer.cpp \
		database.cpp qrc_qml.cpp \
		moc_passwordanalyzer.cpp \
		moc_database.cpp
OBJECTS       = main.o \
		passwordanalyzer.o \
		database.o \
		qrc_qml.o \
		moc_passwordanalyzer.o \
		moc_database.o
DIST          = /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		PasswordGuard.pro passwordanalyzer.h \
		database.h main.cpp \
		passwordanalyzer.cpp \
		database.cpp
QMAKE_TARGET  = PasswordGuard
DESTDIR       = 
TARGET        = PasswordGuard


first: all
####### Build rules

PasswordGuard:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PasswordGuard.pro /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		PasswordGuard.pro \
		qml.qrc
	$(QMAKE) -o Makefile PasswordGuard.pro -spec linux-g++ CONFIG+=debug
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf:
/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf:
PasswordGuard.pro:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile PasswordGuard.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile PasswordGuard

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents passwordanalyzer.h database.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp passwordanalyzer.cpp database.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/home/halilibrahim/Qt/5.15.2/gcc_64/bin/rcc \
		main.qml \
		data/Pwdb_top-1000.txt
	/home/halilibrahim/Qt/5.15.2/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -Wextra -dM -E -o moc_predefs.h /home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_passwordanalyzer.cpp moc_database.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_passwordanalyzer.cpp moc_database.cpp
moc_passwordanalyzer.cpp: passwordanalyzer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QSet \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantMap \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QStringList \
		moc_predefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/bin/moc
	/home/halilibrahim/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /media/halilibrahim/yeni_birim/QT_Projeler/PasswordGuard/moc_predefs.h -I/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/media/halilibrahim/yeni_birim/QT_Projeler/PasswordGuard -I/home/halilibrahim/Qt/5.15.2/gcc_64/include -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQuick -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQmlModels -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include passwordanalyzer.h -o moc_passwordanalyzer.cpp

moc_database.cpp: database.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantList \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantMap \
		moc_predefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/bin/moc
	/home/halilibrahim/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /media/halilibrahim/yeni_birim/QT_Projeler/PasswordGuard/moc_predefs.h -I/home/halilibrahim/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/media/halilibrahim/yeni_birim/QT_Projeler/PasswordGuard -I/home/halilibrahim/Qt/5.15.2/gcc_64/include -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQuick -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQmlModels -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql -I/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include database.h -o moc_database.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/QGuiApplication \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/QQmlApplicationEngine \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlapplicationengine.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlengine.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qjsengine.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qjsvalue.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qtqmlglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qtqml-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmldebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqml.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlprivate.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlparserstatus.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmllist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetaobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlerror.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/QQmlContext \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtQml/qqmlcontext.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/QIcon \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		passwordanalyzer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QSet \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantMap \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QStringList \
		database.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

passwordanalyzer.o: passwordanalyzer.cpp passwordanalyzer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QSet \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantMap \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QStringList \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QFile \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QTextStream \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QDebug \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QtGlobal
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passwordanalyzer.o passwordanalyzer.cpp

database.o: database.cpp database.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/QSqlDatabase \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qsqldatabase.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsqlglobal.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qtsql-config.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantList \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QVariantMap \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/QSqlError \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qsqlerror.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/QSqlQuery \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtSql/qsqlquery.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QStandardPaths \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qstandardpaths.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QDir \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdir.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qfileinfo.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QDateTime \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/qdatetime.h \
		/home/halilibrahim/Qt/5.15.2/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_passwordanalyzer.o: moc_passwordanalyzer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passwordanalyzer.o moc_passwordanalyzer.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PasswordGuard/bin || mkdir -p $(INSTALL_ROOT)/opt/PasswordGuard/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/PasswordGuard/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/PasswordGuard/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PasswordGuard/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

